name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true
workers_dev = false

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloud_mail_db"
database_id = "ce19a691-1c8a-4435-a31a-034b3e9dd1e9"

[[kv_namespaces]]
binding = "kv"
id = "9bec4da6367e4aca984648e02d1d739c"

[[r2_buckets]]
binding = "r2"
bucket_name = "cloud-mail-r2"

[[send_email]]
name = "email"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 * * * *"]

[vars]
domain = ["205.dpdns.org"]
admin = ""
jwt_secret = ""

routes = [
  { pattern = "mail.205.dpdns.org", custom_domain = true }
]

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"